apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: tag-new-vms
spec:
  filter:
    attributes:
      type: com.vmware.vsphere.VmBeingCreatedEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: tag-new-vms
